// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _slam_planner_HighState_h
#define _slam_planner_HighState_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "slam_planner_uint8_t.h"
#include "slam_planner_uint16_t.h"
#include "slam_planner_uint16_t.h"
#include "slam_planner_uint32_t.h"
#include "slam_planner_uint8_t.h"
#include "slam_planner_uint8_t.h"
#include "slam_planner_IMU.h"
#include "slam_planner_Cartesian.h"
#include "slam_planner_Cartesian.h"
#include "slam_planner_uint32_t.h"
#include "slam_planner_uint8_t.h"
#include "slam_planner_uint32_t.h"
#include "slam_planner_uint32_t.h"
typedef struct _slam_planner_HighState slam_planner_HighState;
struct _slam_planner_HighState
{
    slam_planner_uint8_t levelFlag;
    slam_planner_uint16_t commVersion;
    slam_planner_uint16_t robotID;
    slam_planner_uint32_t SN;
    slam_planner_uint8_t bandWidth;
    slam_planner_uint8_t mode;
    slam_planner_IMU imu;
    float      forwardSpeed;
    float      sideSpeed;
    float      rotateSpeed;
    float      bodyHeight;
    float      updownSpeed;
    float      forwardPosition;
    float      sidePosition;
    slam_planner_Cartesian footPosition2Body[4];
    slam_planner_Cartesian footSpeed2Body[4];
    int16_t    footForce[4];
    int16_t    footForceEst[4];
    slam_planner_uint32_t tick;
    slam_planner_uint8_t wirelessRemote[40];
    slam_planner_uint32_t reserve;
    slam_planner_uint32_t crc;
};

/**
 * Create a deep copy of a slam_planner_HighState.
 * When no longer needed, destroy it with slam_planner_HighState_destroy()
 */
slam_planner_HighState* slam_planner_HighState_copy(const slam_planner_HighState* to_copy);

/**
 * Destroy an instance of slam_planner_HighState created by slam_planner_HighState_copy()
 */
void slam_planner_HighState_destroy(slam_planner_HighState* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _slam_planner_HighState_subscription_t slam_planner_HighState_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * slam_planner_HighState is received.
 */
typedef void(*slam_planner_HighState_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const slam_planner_HighState *msg, void *userdata);

/**
 * Publish a message of type slam_planner_HighState using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int slam_planner_HighState_publish(lcm_t *lcm, const char *channel, const slam_planner_HighState *msg);

/**
 * Subscribe to messages of type slam_planner_HighState using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
slam_planner_HighState_subscription_t* slam_planner_HighState_subscribe(
    lcm_t *lcm, const char *channel, slam_planner_HighState_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by slam_planner_HighState_subscribe()
 */
int slam_planner_HighState_unsubscribe(lcm_t *lcm, slam_planner_HighState_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int slam_planner_HighState_subscription_set_queue_capacity(
    slam_planner_HighState_subscription_t* subs, int num_messages);

/**
 * Encode a message of type slam_planner_HighState into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to slam_planner_HighState_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int slam_planner_HighState_encode(void *buf, int offset, int maxlen, const slam_planner_HighState *p);

/**
 * Decode a message of type slam_planner_HighState from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with slam_planner_HighState_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int slam_planner_HighState_decode(const void *buf, int offset, int maxlen, slam_planner_HighState *msg);

/**
 * Release resources allocated by slam_planner_HighState_decode()
 * @return 0
 */
int slam_planner_HighState_decode_cleanup(slam_planner_HighState *p);

/**
 * Check how many bytes are required to encode a message of type slam_planner_HighState
 */
int slam_planner_HighState_encoded_size(const slam_planner_HighState *p);

// LCM support functions. Users should not call these
int64_t __slam_planner_HighState_get_hash(void);
uint64_t __slam_planner_HighState_hash_recursive(const __lcm_hash_ptr *p);
int __slam_planner_HighState_encode_array(
    void *buf, int offset, int maxlen, const slam_planner_HighState *p, int elements);
int __slam_planner_HighState_decode_array(
    const void *buf, int offset, int maxlen, slam_planner_HighState *p, int elements);
int __slam_planner_HighState_decode_array_cleanup(slam_planner_HighState *p, int elements);
int __slam_planner_HighState_encoded_array_size(const slam_planner_HighState *p, int elements);
int __slam_planner_HighState_clone_array(const slam_planner_HighState *p, slam_planner_HighState *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
