// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _slam_planner_Cartesian_h
#define _slam_planner_Cartesian_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _slam_planner_Cartesian slam_planner_Cartesian;
struct _slam_planner_Cartesian
{
    float      x;
    float      y;
    float      z;
};

/**
 * Create a deep copy of a slam_planner_Cartesian.
 * When no longer needed, destroy it with slam_planner_Cartesian_destroy()
 */
slam_planner_Cartesian* slam_planner_Cartesian_copy(const slam_planner_Cartesian* to_copy);

/**
 * Destroy an instance of slam_planner_Cartesian created by slam_planner_Cartesian_copy()
 */
void slam_planner_Cartesian_destroy(slam_planner_Cartesian* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _slam_planner_Cartesian_subscription_t slam_planner_Cartesian_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * slam_planner_Cartesian is received.
 */
typedef void(*slam_planner_Cartesian_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const slam_planner_Cartesian *msg, void *userdata);

/**
 * Publish a message of type slam_planner_Cartesian using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int slam_planner_Cartesian_publish(lcm_t *lcm, const char *channel, const slam_planner_Cartesian *msg);

/**
 * Subscribe to messages of type slam_planner_Cartesian using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
slam_planner_Cartesian_subscription_t* slam_planner_Cartesian_subscribe(
    lcm_t *lcm, const char *channel, slam_planner_Cartesian_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by slam_planner_Cartesian_subscribe()
 */
int slam_planner_Cartesian_unsubscribe(lcm_t *lcm, slam_planner_Cartesian_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int slam_planner_Cartesian_subscription_set_queue_capacity(
    slam_planner_Cartesian_subscription_t* subs, int num_messages);

/**
 * Encode a message of type slam_planner_Cartesian into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to slam_planner_Cartesian_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int slam_planner_Cartesian_encode(void *buf, int offset, int maxlen, const slam_planner_Cartesian *p);

/**
 * Decode a message of type slam_planner_Cartesian from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with slam_planner_Cartesian_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int slam_planner_Cartesian_decode(const void *buf, int offset, int maxlen, slam_planner_Cartesian *msg);

/**
 * Release resources allocated by slam_planner_Cartesian_decode()
 * @return 0
 */
int slam_planner_Cartesian_decode_cleanup(slam_planner_Cartesian *p);

/**
 * Check how many bytes are required to encode a message of type slam_planner_Cartesian
 */
int slam_planner_Cartesian_encoded_size(const slam_planner_Cartesian *p);

// LCM support functions. Users should not call these
int64_t __slam_planner_Cartesian_get_hash(void);
uint64_t __slam_planner_Cartesian_hash_recursive(const __lcm_hash_ptr *p);
int __slam_planner_Cartesian_encode_array(
    void *buf, int offset, int maxlen, const slam_planner_Cartesian *p, int elements);
int __slam_planner_Cartesian_decode_array(
    const void *buf, int offset, int maxlen, slam_planner_Cartesian *p, int elements);
int __slam_planner_Cartesian_decode_array_cleanup(slam_planner_Cartesian *p, int elements);
int __slam_planner_Cartesian_encoded_array_size(const slam_planner_Cartesian *p, int elements);
int __slam_planner_Cartesian_clone_array(const slam_planner_Cartesian *p, slam_planner_Cartesian *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
