/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package slam_planner;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class IMU implements lcm.lcm.LCMEncodable
{
    public float quaternion[];
    public float gyroscope[];
    public float accelerometer[];
    public float rpy[];
    public byte temperature;
 
    public IMU()
    {
        quaternion = new float[4];
        gyroscope = new float[3];
        accelerometer = new float[3];
        rpy = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x53a6be455f9e22faL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(slam_planner.IMU.class))
            return 0L;
 
        classes.add(slam_planner.IMU.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quaternion[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.gyroscope[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.accelerometer[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        outs.writeByte(this.temperature); 
 
    }
 
    public IMU(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public IMU(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static slam_planner.IMU _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        slam_planner.IMU o = new slam_planner.IMU();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.quaternion = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quaternion[a] = ins.readFloat();
        }
 
        this.gyroscope = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gyroscope[a] = ins.readFloat();
        }
 
        this.accelerometer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.accelerometer[a] = ins.readFloat();
        }
 
        this.rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.temperature = ins.readByte();
 
    }
 
    public slam_planner.IMU copy()
    {
        slam_planner.IMU outobj = new slam_planner.IMU();
        outobj.quaternion = new float[(int) 4];
        System.arraycopy(this.quaternion, 0, outobj.quaternion, 0, 4); 
        outobj.gyroscope = new float[(int) 3];
        System.arraycopy(this.gyroscope, 0, outobj.gyroscope, 0, 3); 
        outobj.accelerometer = new float[(int) 3];
        System.arraycopy(this.accelerometer, 0, outobj.accelerometer, 0, 3); 
        outobj.rpy = new float[(int) 3];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 3); 
        outobj.temperature = this.temperature;
 
        return outobj;
    }
 
}

