/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __slam_planner_HighState_hpp__
#define __slam_planner_HighState_hpp__

#include <lcm/lcm_coretypes.h>

#include "slam_planner/uint8_t.hpp"
#include "slam_planner/uint16_t.hpp"
#include "slam_planner/uint16_t.hpp"
#include "slam_planner/uint32_t.hpp"
#include "slam_planner/uint8_t.hpp"
#include "slam_planner/uint8_t.hpp"
#include "slam_planner/IMU.hpp"
#include "slam_planner/Cartesian.hpp"
#include "slam_planner/Cartesian.hpp"
#include "slam_planner/uint32_t.hpp"
#include "slam_planner/uint8_t.hpp"
#include "slam_planner/uint32_t.hpp"
#include "slam_planner/uint32_t.hpp"

namespace slam_planner
{

class HighState
{
    public:
        slam_planner::uint8_t levelFlag;

        slam_planner::uint16_t commVersion;

        slam_planner::uint16_t robotID;

        slam_planner::uint32_t SN;

        slam_planner::uint8_t bandWidth;

        slam_planner::uint8_t mode;

        slam_planner::IMU imu;

        float      forwardSpeed;

        float      sideSpeed;

        float      rotateSpeed;

        float      bodyHeight;

        float      updownSpeed;

        float      forwardPosition;

        float      sidePosition;

        slam_planner::Cartesian footPosition2Body[4];

        slam_planner::Cartesian footSpeed2Body[4];

        int16_t    footForce[4];

        int16_t    footForceEst[4];

        slam_planner::uint32_t tick;

        slam_planner::uint8_t wirelessRemote[40];

        slam_planner::uint32_t reserve;

        slam_planner::uint32_t crc;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "HighState"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int HighState::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int HighState::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int HighState::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t HighState::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* HighState::getTypeName()
{
    return "HighState";
}

int HighState::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->levelFlag._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->commVersion._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->robotID._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->SN._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->bandWidth._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mode._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->imu._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->forwardSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->sideSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->rotateSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->bodyHeight, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->updownSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->forwardPosition, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->sidePosition, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = this->footPosition2Body[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = this->footSpeed2Body[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->footForce[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->footForceEst[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->tick._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 40; a0++) {
        tlen = this->wirelessRemote[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->reserve._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->crc._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int HighState::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->levelFlag._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->commVersion._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->robotID._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->SN._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->bandWidth._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->mode._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->imu._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->forwardSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->sideSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->rotateSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->bodyHeight, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->updownSpeed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->forwardPosition, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->sidePosition, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = this->footPosition2Body[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < 4; a0++) {
        tlen = this->footSpeed2Body[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->footForce[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->footForceEst[0], 4);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->tick._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 40; a0++) {
        tlen = this->wirelessRemote[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->reserve._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->crc._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int HighState::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->levelFlag._getEncodedSizeNoHash();
    enc_size += this->commVersion._getEncodedSizeNoHash();
    enc_size += this->robotID._getEncodedSizeNoHash();
    enc_size += this->SN._getEncodedSizeNoHash();
    enc_size += this->bandWidth._getEncodedSizeNoHash();
    enc_size += this->mode._getEncodedSizeNoHash();
    enc_size += this->imu._getEncodedSizeNoHash();
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < 4; a0++) {
        enc_size += this->footPosition2Body[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < 4; a0++) {
        enc_size += this->footSpeed2Body[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int16_t_encoded_array_size(NULL, 4);
    enc_size += __int16_t_encoded_array_size(NULL, 4);
    enc_size += this->tick._getEncodedSizeNoHash();
    for (int a0 = 0; a0 < 40; a0++) {
        enc_size += this->wirelessRemote[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->reserve._getEncodedSizeNoHash();
    enc_size += this->crc._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t HighState::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == HighState::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, HighState::getHash };

    uint64_t hash = 0x421e999e5a704408LL +
         slam_planner::uint8_t::_computeHash(&cp) +
         slam_planner::uint16_t::_computeHash(&cp) +
         slam_planner::uint16_t::_computeHash(&cp) +
         slam_planner::uint32_t::_computeHash(&cp) +
         slam_planner::uint8_t::_computeHash(&cp) +
         slam_planner::uint8_t::_computeHash(&cp) +
         slam_planner::IMU::_computeHash(&cp) +
         slam_planner::Cartesian::_computeHash(&cp) +
         slam_planner::Cartesian::_computeHash(&cp) +
         slam_planner::uint32_t::_computeHash(&cp) +
         slam_planner::uint8_t::_computeHash(&cp) +
         slam_planner::uint32_t::_computeHash(&cp) +
         slam_planner::uint32_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
