// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "slam_planner_HighState.h"

static int __slam_planner_HighState_hash_computed;
static uint64_t __slam_planner_HighState_hash;

uint64_t __slam_planner_HighState_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __slam_planner_HighState_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __slam_planner_HighState_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x421e999e5a704408LL
         + __slam_planner_uint8_t_hash_recursive(&cp)
         + __slam_planner_uint16_t_hash_recursive(&cp)
         + __slam_planner_uint16_t_hash_recursive(&cp)
         + __slam_planner_uint32_t_hash_recursive(&cp)
         + __slam_planner_uint8_t_hash_recursive(&cp)
         + __slam_planner_uint8_t_hash_recursive(&cp)
         + __slam_planner_IMU_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __slam_planner_Cartesian_hash_recursive(&cp)
         + __slam_planner_Cartesian_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __slam_planner_uint32_t_hash_recursive(&cp)
         + __slam_planner_uint8_t_hash_recursive(&cp)
         + __slam_planner_uint32_t_hash_recursive(&cp)
         + __slam_planner_uint32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __slam_planner_HighState_get_hash(void)
{
    if (!__slam_planner_HighState_hash_computed) {
        __slam_planner_HighState_hash = (int64_t)__slam_planner_HighState_hash_recursive(NULL);
        __slam_planner_HighState_hash_computed = 1;
    }

    return __slam_planner_HighState_hash;
}

int __slam_planner_HighState_encode_array(void *buf, int offset, int maxlen, const slam_planner_HighState *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __slam_planner_uint8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].levelFlag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].commVersion), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].robotID), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].SN), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bandWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_IMU_encode_array(buf, offset + pos, maxlen - pos, &(p[element].imu), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].forwardSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].sideSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rotateSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bodyHeight), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].updownSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].forwardPosition), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].sidePosition), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_Cartesian_encode_array(buf, offset + pos, maxlen - pos, p[element].footPosition2Body, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_Cartesian_encode_array(buf, offset + pos, maxlen - pos, p[element].footSpeed2Body, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].footForce, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].footForceEst, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].tick), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].wirelessRemote, 40);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].reserve), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].crc), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int slam_planner_HighState_encode(void *buf, int offset, int maxlen, const slam_planner_HighState *p)
{
    int pos = 0, thislen;
    int64_t hash = __slam_planner_HighState_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __slam_planner_HighState_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __slam_planner_HighState_encoded_array_size(const slam_planner_HighState *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __slam_planner_uint8_t_encoded_array_size(&(p[element].levelFlag), 1);

        size += __slam_planner_uint16_t_encoded_array_size(&(p[element].commVersion), 1);

        size += __slam_planner_uint16_t_encoded_array_size(&(p[element].robotID), 1);

        size += __slam_planner_uint32_t_encoded_array_size(&(p[element].SN), 1);

        size += __slam_planner_uint8_t_encoded_array_size(&(p[element].bandWidth), 1);

        size += __slam_planner_uint8_t_encoded_array_size(&(p[element].mode), 1);

        size += __slam_planner_IMU_encoded_array_size(&(p[element].imu), 1);

        size += __float_encoded_array_size(&(p[element].forwardSpeed), 1);

        size += __float_encoded_array_size(&(p[element].sideSpeed), 1);

        size += __float_encoded_array_size(&(p[element].rotateSpeed), 1);

        size += __float_encoded_array_size(&(p[element].bodyHeight), 1);

        size += __float_encoded_array_size(&(p[element].updownSpeed), 1);

        size += __float_encoded_array_size(&(p[element].forwardPosition), 1);

        size += __float_encoded_array_size(&(p[element].sidePosition), 1);

        size += __slam_planner_Cartesian_encoded_array_size(p[element].footPosition2Body, 4);

        size += __slam_planner_Cartesian_encoded_array_size(p[element].footSpeed2Body, 4);

        size += __int16_t_encoded_array_size(p[element].footForce, 4);

        size += __int16_t_encoded_array_size(p[element].footForceEst, 4);

        size += __slam_planner_uint32_t_encoded_array_size(&(p[element].tick), 1);

        size += __slam_planner_uint8_t_encoded_array_size(p[element].wirelessRemote, 40);

        size += __slam_planner_uint32_t_encoded_array_size(&(p[element].reserve), 1);

        size += __slam_planner_uint32_t_encoded_array_size(&(p[element].crc), 1);

    }
    return size;
}

int slam_planner_HighState_encoded_size(const slam_planner_HighState *p)
{
    return 8 + __slam_planner_HighState_encoded_array_size(p, 1);
}

int __slam_planner_HighState_decode_array(const void *buf, int offset, int maxlen, slam_planner_HighState *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __slam_planner_uint8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].levelFlag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].commVersion), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].robotID), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].SN), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bandWidth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mode), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_IMU_decode_array(buf, offset + pos, maxlen - pos, &(p[element].imu), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].forwardSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].sideSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rotateSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bodyHeight), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].updownSpeed), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].forwardPosition), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].sidePosition), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_Cartesian_decode_array(buf, offset + pos, maxlen - pos, p[element].footPosition2Body, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_Cartesian_decode_array(buf, offset + pos, maxlen - pos, p[element].footSpeed2Body, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].footForce, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].footForceEst, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].tick), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].wirelessRemote, 40);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].reserve), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __slam_planner_uint32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].crc), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __slam_planner_HighState_decode_array_cleanup(slam_planner_HighState *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __slam_planner_uint8_t_decode_array_cleanup(&(p[element].levelFlag), 1);

        __slam_planner_uint16_t_decode_array_cleanup(&(p[element].commVersion), 1);

        __slam_planner_uint16_t_decode_array_cleanup(&(p[element].robotID), 1);

        __slam_planner_uint32_t_decode_array_cleanup(&(p[element].SN), 1);

        __slam_planner_uint8_t_decode_array_cleanup(&(p[element].bandWidth), 1);

        __slam_planner_uint8_t_decode_array_cleanup(&(p[element].mode), 1);

        __slam_planner_IMU_decode_array_cleanup(&(p[element].imu), 1);

        __float_decode_array_cleanup(&(p[element].forwardSpeed), 1);

        __float_decode_array_cleanup(&(p[element].sideSpeed), 1);

        __float_decode_array_cleanup(&(p[element].rotateSpeed), 1);

        __float_decode_array_cleanup(&(p[element].bodyHeight), 1);

        __float_decode_array_cleanup(&(p[element].updownSpeed), 1);

        __float_decode_array_cleanup(&(p[element].forwardPosition), 1);

        __float_decode_array_cleanup(&(p[element].sidePosition), 1);

        __slam_planner_Cartesian_decode_array_cleanup(p[element].footPosition2Body, 4);

        __slam_planner_Cartesian_decode_array_cleanup(p[element].footSpeed2Body, 4);

        __int16_t_decode_array_cleanup(p[element].footForce, 4);

        __int16_t_decode_array_cleanup(p[element].footForceEst, 4);

        __slam_planner_uint32_t_decode_array_cleanup(&(p[element].tick), 1);

        __slam_planner_uint8_t_decode_array_cleanup(p[element].wirelessRemote, 40);

        __slam_planner_uint32_t_decode_array_cleanup(&(p[element].reserve), 1);

        __slam_planner_uint32_t_decode_array_cleanup(&(p[element].crc), 1);

    }
    return 0;
}

int slam_planner_HighState_decode(const void *buf, int offset, int maxlen, slam_planner_HighState *p)
{
    int pos = 0, thislen;
    int64_t hash = __slam_planner_HighState_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __slam_planner_HighState_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int slam_planner_HighState_decode_cleanup(slam_planner_HighState *p)
{
    return __slam_planner_HighState_decode_array_cleanup(p, 1);
}

int __slam_planner_HighState_clone_array(const slam_planner_HighState *p, slam_planner_HighState *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __slam_planner_uint8_t_clone_array(&(p[element].levelFlag), &(q[element].levelFlag), 1);

        __slam_planner_uint16_t_clone_array(&(p[element].commVersion), &(q[element].commVersion), 1);

        __slam_planner_uint16_t_clone_array(&(p[element].robotID), &(q[element].robotID), 1);

        __slam_planner_uint32_t_clone_array(&(p[element].SN), &(q[element].SN), 1);

        __slam_planner_uint8_t_clone_array(&(p[element].bandWidth), &(q[element].bandWidth), 1);

        __slam_planner_uint8_t_clone_array(&(p[element].mode), &(q[element].mode), 1);

        __slam_planner_IMU_clone_array(&(p[element].imu), &(q[element].imu), 1);

        __float_clone_array(&(p[element].forwardSpeed), &(q[element].forwardSpeed), 1);

        __float_clone_array(&(p[element].sideSpeed), &(q[element].sideSpeed), 1);

        __float_clone_array(&(p[element].rotateSpeed), &(q[element].rotateSpeed), 1);

        __float_clone_array(&(p[element].bodyHeight), &(q[element].bodyHeight), 1);

        __float_clone_array(&(p[element].updownSpeed), &(q[element].updownSpeed), 1);

        __float_clone_array(&(p[element].forwardPosition), &(q[element].forwardPosition), 1);

        __float_clone_array(&(p[element].sidePosition), &(q[element].sidePosition), 1);

        __slam_planner_Cartesian_clone_array(p[element].footPosition2Body, q[element].footPosition2Body, 4);

        __slam_planner_Cartesian_clone_array(p[element].footSpeed2Body, q[element].footSpeed2Body, 4);

        __int16_t_clone_array(p[element].footForce, q[element].footForce, 4);

        __int16_t_clone_array(p[element].footForceEst, q[element].footForceEst, 4);

        __slam_planner_uint32_t_clone_array(&(p[element].tick), &(q[element].tick), 1);

        __slam_planner_uint8_t_clone_array(p[element].wirelessRemote, q[element].wirelessRemote, 40);

        __slam_planner_uint32_t_clone_array(&(p[element].reserve), &(q[element].reserve), 1);

        __slam_planner_uint32_t_clone_array(&(p[element].crc), &(q[element].crc), 1);

    }
    return 0;
}

slam_planner_HighState *slam_planner_HighState_copy(const slam_planner_HighState *p)
{
    slam_planner_HighState *q = (slam_planner_HighState*) malloc(sizeof(slam_planner_HighState));
    __slam_planner_HighState_clone_array(p, q, 1);
    return q;
}

void slam_planner_HighState_destroy(slam_planner_HighState *p)
{
    __slam_planner_HighState_decode_array_cleanup(p, 1);
    free(p);
}

int slam_planner_HighState_publish(lcm_t *lc, const char *channel, const slam_planner_HighState *p)
{
      int max_data_size = slam_planner_HighState_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = slam_planner_HighState_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _slam_planner_HighState_subscription_t {
    slam_planner_HighState_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void slam_planner_HighState_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    slam_planner_HighState p;
    memset(&p, 0, sizeof(slam_planner_HighState));
    status = slam_planner_HighState_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding slam_planner_HighState!!!\n", status);
        return;
    }

    slam_planner_HighState_subscription_t *h = (slam_planner_HighState_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    slam_planner_HighState_decode_cleanup (&p);
}

slam_planner_HighState_subscription_t* slam_planner_HighState_subscribe (lcm_t *lcm,
                    const char *channel,
                    slam_planner_HighState_handler_t f, void *userdata)
{
    slam_planner_HighState_subscription_t *n = (slam_planner_HighState_subscription_t*)
                       malloc(sizeof(slam_planner_HighState_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 slam_planner_HighState_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg slam_planner_HighState LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int slam_planner_HighState_subscription_set_queue_capacity (slam_planner_HighState_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int slam_planner_HighState_unsubscribe(lcm_t *lcm, slam_planner_HighState_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe slam_planner_HighState_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

