// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "slam_planner_IMU.h"

static int __slam_planner_IMU_hash_computed;
static uint64_t __slam_planner_IMU_hash;

uint64_t __slam_planner_IMU_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __slam_planner_IMU_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __slam_planner_IMU_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x53a6be455f9e22faLL
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __slam_planner_IMU_get_hash(void)
{
    if (!__slam_planner_IMU_hash_computed) {
        __slam_planner_IMU_hash = (int64_t)__slam_planner_IMU_hash_recursive(NULL);
        __slam_planner_IMU_hash_computed = 1;
    }

    return __slam_planner_IMU_hash;
}

int __slam_planner_IMU_encode_array(void *buf, int offset, int maxlen, const slam_planner_IMU *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].quaternion, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].gyroscope, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].accelerometer, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].rpy, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].temperature), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int slam_planner_IMU_encode(void *buf, int offset, int maxlen, const slam_planner_IMU *p)
{
    int pos = 0, thislen;
    int64_t hash = __slam_planner_IMU_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __slam_planner_IMU_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __slam_planner_IMU_encoded_array_size(const slam_planner_IMU *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __float_encoded_array_size(p[element].quaternion, 4);

        size += __float_encoded_array_size(p[element].gyroscope, 3);

        size += __float_encoded_array_size(p[element].accelerometer, 3);

        size += __float_encoded_array_size(p[element].rpy, 3);

        size += __int8_t_encoded_array_size(&(p[element].temperature), 1);

    }
    return size;
}

int slam_planner_IMU_encoded_size(const slam_planner_IMU *p)
{
    return 8 + __slam_planner_IMU_encoded_array_size(p, 1);
}

int __slam_planner_IMU_decode_array(const void *buf, int offset, int maxlen, slam_planner_IMU *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].quaternion, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].gyroscope, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].accelerometer, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].rpy, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].temperature), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __slam_planner_IMU_decode_array_cleanup(slam_planner_IMU *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_decode_array_cleanup(p[element].quaternion, 4);

        __float_decode_array_cleanup(p[element].gyroscope, 3);

        __float_decode_array_cleanup(p[element].accelerometer, 3);

        __float_decode_array_cleanup(p[element].rpy, 3);

        __int8_t_decode_array_cleanup(&(p[element].temperature), 1);

    }
    return 0;
}

int slam_planner_IMU_decode(const void *buf, int offset, int maxlen, slam_planner_IMU *p)
{
    int pos = 0, thislen;
    int64_t hash = __slam_planner_IMU_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __slam_planner_IMU_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int slam_planner_IMU_decode_cleanup(slam_planner_IMU *p)
{
    return __slam_planner_IMU_decode_array_cleanup(p, 1);
}

int __slam_planner_IMU_clone_array(const slam_planner_IMU *p, slam_planner_IMU *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __float_clone_array(p[element].quaternion, q[element].quaternion, 4);

        __float_clone_array(p[element].gyroscope, q[element].gyroscope, 3);

        __float_clone_array(p[element].accelerometer, q[element].accelerometer, 3);

        __float_clone_array(p[element].rpy, q[element].rpy, 3);

        __int8_t_clone_array(&(p[element].temperature), &(q[element].temperature), 1);

    }
    return 0;
}

slam_planner_IMU *slam_planner_IMU_copy(const slam_planner_IMU *p)
{
    slam_planner_IMU *q = (slam_planner_IMU*) malloc(sizeof(slam_planner_IMU));
    __slam_planner_IMU_clone_array(p, q, 1);
    return q;
}

void slam_planner_IMU_destroy(slam_planner_IMU *p)
{
    __slam_planner_IMU_decode_array_cleanup(p, 1);
    free(p);
}

int slam_planner_IMU_publish(lcm_t *lc, const char *channel, const slam_planner_IMU *p)
{
      int max_data_size = slam_planner_IMU_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = slam_planner_IMU_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _slam_planner_IMU_subscription_t {
    slam_planner_IMU_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void slam_planner_IMU_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    slam_planner_IMU p;
    memset(&p, 0, sizeof(slam_planner_IMU));
    status = slam_planner_IMU_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding slam_planner_IMU!!!\n", status);
        return;
    }

    slam_planner_IMU_subscription_t *h = (slam_planner_IMU_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    slam_planner_IMU_decode_cleanup (&p);
}

slam_planner_IMU_subscription_t* slam_planner_IMU_subscribe (lcm_t *lcm,
                    const char *channel,
                    slam_planner_IMU_handler_t f, void *userdata)
{
    slam_planner_IMU_subscription_t *n = (slam_planner_IMU_subscription_t*)
                       malloc(sizeof(slam_planner_IMU_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 slam_planner_IMU_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg slam_planner_IMU LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int slam_planner_IMU_subscription_set_queue_capacity (slam_planner_IMU_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int slam_planner_IMU_unsubscribe(lcm_t *lcm, slam_planner_IMU_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe slam_planner_IMU_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

